name: RivalMC-PaperCore
main: cc.rivalmc.papercore.CorePlugin
description: >
  The core plugin for RivalMC's Paper servers, providing staff tools, essentials commands,
  chat formatting, player profiles, punishment systems, and more.

version: '1.0'
api-version: '1.19'

website: https://store.rivalmc.cc

authors:
  - Babyless
  - flennium
  - hubailmn
  - RivalMC
  - RobloxChild

libraries:
  - "net.dv8tion:JDA:5.6.1"
  - "com.github.ben-manes.caffeine:caffeine:3.2.0"
  - "org.graalvm.js:js-scriptengine:24.2.1"
  - "org.graalvm.js:js-language:24.2.1"

depend:
  - WorldGuard
  - WGRegionEvents

softdepend:
  - PlaceholderAPI